import type { Metadata } from "next"
import "./globals.css"

/* import components */
import Header from "../src/components/Header"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="dark_mode">
        <Header />
				{children}
			</body>
		</html>
	)
}
