import React from "react";
import type { Metadata } from "next"

import Hero from "@/src/components/home/Hero"
import Projects from "@/src/components/home/Projects"
import Skills from "@/src/components/home/Skills";

export const metadata: Metadata = {
	title: "Pierre Gaillard, développeur web à Vannes",
	description: "Generated by create next app",
}

export default function Home() {
  return (
    <React.Fragment>
      <Hero />
      <Projects />
      <Skills />
    </React.Fragment>
  );
}
